language: node_js
node_js:
 - "node"
env:
 global:
 - CODECLIMATE_REPO_TOKEN=a863eeec1651fec18594c74410d73c62a6f091aec0bd63c82884f9dbf71ab09b
services:
 - postgresql
cache:
  directories:
    - "node_modules"
before_script:
 - cat .env.travis >> .env
 - psql -c 'CREATE DATABASE "bookmeal";' -U postgres
 - psql -c "CREATE USER root WITH PASSWORD 'imoleayo';" -U postgres
after_success:
  - npm run coverage
